# mkdocs.yml in deinem Docs-Repo

site_name: SLAM Docs
# URL zur fertigen Seite (GitHub Pages URL des Docs-Repos)
site_url: https://docs.learn-smart.app

# WICHTIG: Hier die URL zum ECHTEN App-Code eintragen, nicht zum Docs-Repo
repo_url: https://github.com/Seminarkurs-Lernapp-Mathematik/slam-app
repo_name: GitHub # Text neben dem Icon

theme:
  name: shadcn
  # Optional: Logo/Favicon, falls du welche hast
  # logo: assets/logo.png
  # favicon: assets/favicon.png

  # Features aktivieren (ähnlich wie bei Material)
  features:
    - navigation.instant
    - navigation.tabs # Top-Navigation statt Sidebar (geschmackssache)
    - search.suggest
    - search.highlight

# Plugins, die das Theme unterstützt/benötigt
plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition # Für Info-Boxen (!!! note)
